repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'uv run pytest --no-header -rN; ret=$?; [ $ret -eq 5 ] && exit 0 || exit $ret'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
